# Generated by Django 3.2.2 on 2021-05-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_botuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='pocket_request_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
