# Generated by Django 3.2.2 on 2021-05-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_botuser_pocket_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
